// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"github.com/zgiai/luas/api/internal/app"
	"github.com/zgiai/luas/api/internal/infra/config"
	"github.com/zgiai/luas/api/internal/infra/database"
	"github.com/zgiai/luas/api/internal/infra/email"
	"github.com/zgiai/luas/api/internal/infra/events"
	"github.com/zgiai/luas/api/internal/infra/jwt"
	"github.com/zgiai/luas/api/internal/infra/migration"
	"github.com/zgiai/luas/api/internal/modules/apikey"
	"github.com/zgiai/luas/api/internal/modules/audit"
	"github.com/zgiai/luas/api/internal/modules/execution"
	"github.com/zgiai/luas/api/internal/modules/githubintegration"
	"github.com/zgiai/luas/api/internal/modules/planning"
	"github.com/zgiai/luas/api/internal/modules/repocontext"
	"github.com/zgiai/luas/api/internal/modules/user"
	"github.com/zgiai/luas/api/internal/modules/verification"
	"github.com/zgiai/luas/api/internal/starter"
)

// Injectors from wire.go:

// InitApplication initializes the entire application with all dependencies.
// This is the single entry point for Wire DI.
func InitApplication() (*app.Application, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := database.NewDB(configConfig)
	if err != nil {
		return nil, err
	}
	service := email.NewService(configConfig)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	handler := audit.NewHandler(auditService)
	apikeyRepository := apikey.NewRepository(db)
	apikeyService := apikey.NewService(apikeyRepository)
	apikeyHandler := apikey.NewHandler(apikeyService)
	planningRepository := planning.NewRepository(db)
	repocontextRepository := repocontext.NewRepository(db)
	planningService := planning.NewService(planningRepository, repocontextRepository, planningRepository)
	planningHandler := planning.NewHandler(planningService)
	githubintegrationRepository := githubintegration.NewRepository(db)
	repositoryClientFactory := githubintegration.NewDefaultRepositoryClientFactory()
	installationTokenProvider := githubintegration.NewDefaultInstallationTokenProvider()
	githubintegrationService := githubintegration.NewService(githubintegrationRepository, planningRepository, repositoryClientFactory, installationTokenProvider)
	repositoryTreeSource := repocontext.NewGitHubRepositoryTreeSource(githubintegrationService)
	repocontextService := repocontext.NewService(repocontextRepository, repositoryTreeSource)
	repocontextHandler := repocontext.NewHandler(repocontextService)
	executionRepository := execution.NewRepository(db)
	repositoryResolver := execution.NewGitHubRepositoryResolver(githubintegrationService)
	codeExecutor := execution.NewDefaultCodeExecutor()
	worktreeManager := execution.NewDefaultWorktreeManager()
	prNodeBranchPreparer := execution.NewGitHubPRNodeBranchPreparer(githubintegrationService)
	prNodeDeliverer := execution.NewGitHubPRNodeDeliverer(githubintegrationService)
	executionService := execution.NewService(executionRepository, planningRepository, repositoryResolver, codeExecutor, worktreeManager, prNodeBranchPreparer, prNodeDeliverer)
	executionHandler := execution.NewHandler(executionService)
	githubintegrationHandler := githubintegration.NewHandler(githubintegrationService)
	verificationRepository := verification.NewRepository(db)
	ciFailureReader := verification.NewGitHubCIFailureReader(githubintegrationService)
	verificationService := verification.NewService(verificationRepository, ciFailureReader)
	verificationHandler := verification.NewHandler(verificationService)
	userRepository := user.NewRepository(db)
	jwtService := jwt.NewService(configConfig)
	userMailer := user.NewUserMailer(service)
	userService := user.NewService(userRepository, userRepository, jwtService, eventBus, userMailer)
	userHandler := user.NewHandler(userService, userService, userService, jwtService, userMailer)
	registry, err := starter.NewDefaultRegistry(handler, apikeyHandler, planningHandler, repocontextHandler, executionHandler, githubintegrationHandler, verificationHandler, userHandler)
	if err != nil {
		return nil, err
	}
	application := &app.Application{
		Config:       configConfig,
		DB:           db,
		EmailService: service,
		EventBus:     eventBus,
		Migrator:     migrator,
		Starters:     registry,
	}
	return application, nil
}

// InitApplicationWithConfig initializes the application using an explicitly supplied config.
// This is primarily used by tests so they can reuse the production DI graph and startup chain.
func InitApplicationWithConfig(cfg *config.Config) (*app.Application, error) {
	db, err := database.NewDB(cfg)
	if err != nil {
		return nil, err
	}
	service := email.NewService(cfg)
	eventBus := events.NewEventBus()
	repository := migration.NewDatabaseRepositoryProvider(db)
	migrator := migration.NewMigratorProvider(repository, db, eventBus)
	auditRepository := audit.NewRepository(db)
	auditService := audit.NewService(auditRepository)
	handler := audit.NewHandler(auditService)
	apikeyRepository := apikey.NewRepository(db)
	apikeyService := apikey.NewService(apikeyRepository)
	apikeyHandler := apikey.NewHandler(apikeyService)
	planningRepository := planning.NewRepository(db)
	repocontextRepository := repocontext.NewRepository(db)
	planningService := planning.NewService(planningRepository, repocontextRepository, planningRepository)
	planningHandler := planning.NewHandler(planningService)
	githubintegrationRepository := githubintegration.NewRepository(db)
	repositoryClientFactory := githubintegration.NewDefaultRepositoryClientFactory()
	installationTokenProvider := githubintegration.NewDefaultInstallationTokenProvider()
	githubintegrationService := githubintegration.NewService(githubintegrationRepository, planningRepository, repositoryClientFactory, installationTokenProvider)
	repositoryTreeSource := repocontext.NewGitHubRepositoryTreeSource(githubintegrationService)
	repocontextService := repocontext.NewService(repocontextRepository, repositoryTreeSource)
	repocontextHandler := repocontext.NewHandler(repocontextService)
	executionRepository := execution.NewRepository(db)
	repositoryResolver := execution.NewGitHubRepositoryResolver(githubintegrationService)
	codeExecutor := execution.NewDefaultCodeExecutor()
	worktreeManager := execution.NewDefaultWorktreeManager()
	prNodeBranchPreparer := execution.NewGitHubPRNodeBranchPreparer(githubintegrationService)
	prNodeDeliverer := execution.NewGitHubPRNodeDeliverer(githubintegrationService)
	executionService := execution.NewService(executionRepository, planningRepository, repositoryResolver, codeExecutor, worktreeManager, prNodeBranchPreparer, prNodeDeliverer)
	executionHandler := execution.NewHandler(executionService)
	githubintegrationHandler := githubintegration.NewHandler(githubintegrationService)
	verificationRepository := verification.NewRepository(db)
	ciFailureReader := verification.NewGitHubCIFailureReader(githubintegrationService)
	verificationService := verification.NewService(verificationRepository, ciFailureReader)
	verificationHandler := verification.NewHandler(verificationService)
	userRepository := user.NewRepository(db)
	jwtService := jwt.NewService(cfg)
	userMailer := user.NewUserMailer(service)
	userService := user.NewService(userRepository, userRepository, jwtService, eventBus, userMailer)
	userHandler := user.NewHandler(userService, userService, userService, jwtService, userMailer)
	registry, err := starter.NewDefaultRegistry(handler, apikeyHandler, planningHandler, repocontextHandler, executionHandler, githubintegrationHandler, verificationHandler, userHandler)
	if err != nil {
		return nil, err
	}
	application := &app.Application{
		Config:       cfg,
		DB:           db,
		EmailService: service,
		EventBus:     eventBus,
		Migrator:     migrator,
		Starters:     registry,
	}
	return application, nil
}
