version: '3.8'

services:
  luas-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luas-web
    restart: unless-stopped
    ports:
      - "2020:2020"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
      - LUAS_API_PROXY_TARGET=http://localhost:2010
      - PORT=2020
      - NEXT_PUBLIC_DEPLOY_API_URL=http://localhost:2010/v1
      - NEXT_PUBLIC_PLATFORM_API_URL=http://localhost:2010/v1
      - NEXT_PUBLIC_APP_URL=http://localhost:2020
